apiVersion: batch/v1
kind: CronJob
metadata:
  name: hiz-test
spec:
  schedule: "* * * * *"
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hiz-test
            image: techakademi/hiztest:1
            command: ["speedtest"]
            args: ["--simple"]
          restartPolicy: OnFailure 
        