apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-hostdizin
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/HstDizinData/NginxWeb