apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-truenas
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.76
    path: /mnt/VeriDeposu/TrnsDizinData/NginxWeb