apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dinamik-claim-nfs
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  